<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Calcufolio.Application\Calcufolio.Application.csproj" />
    <ProjectReference Include="..\Calcufolio.Infrastructure\Calcufolio.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
