<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Calcufolio.Application\Calcufolio.Application.csproj" />
    <ProjectReference Include="..\Calcufolio.Domain\Calcufolio.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
